GET localhost:8080/proxy?ip=kek
Content-Type: */*

###
GET 192.168.2.54/trigger
Content-Type: */*

###
GET http://151.55.205.243:8080/proxy

###
GET https://www.simonecelia.it/be/controllers/gate.php
